add team section
loqumi/reimagined-burgers pull request #4
Opened 2022-08-31 11:53 UTC by loqumi

2022-09-02 09:11 UTC, mrblond1n requested changes

2022-09-02 09:11 UTC, mrblond1n commented on src/script/index.js
> -import './menu.js';
как это изменилось то...

2022-09-02 09:11 UTC, mrblond1n commented on src/styles/blocks/index.css
> +@import "team.css";
а как ты определяешь куда именно добавлять импорт? в какую строчку

2022-09-02 15:51 UTC, loqumi commented on src/styles/blocks/index.css
> +@import "team.css";
расставляю по порядку секций

2022-09-06 08:18 UTC, mrblond1n requested changes

2022-09-06 08:18 UTC, mrblond1n commented on src/styles/blocks/index.css
> +@import "team.css";
menu > footer > preview, по порядку?)

Попробуй делать сортировку по алфавиту, порядок секций может меняться, а алфавит остается

2022-09-06 08:18 UTC, mrblond1n commented on src/script/index.js
> +import './slider.js';
здесь тоже можно использовать сортировку по алфавиту

2022-09-06 08:28 UTC, mrblond1n requested changes

2022-09-06 08:28 UTC, mrblond1n commented on src/script/index.js
> +import './slider.js';
что тут поменялось то

2022-09-06 08:28 UTC, mrblond1n commented on src/script/order.js
> +                    answ_window.classList.toggle('true');
что это за класс такой и зачем он нужен?

2022-09-06 08:28 UTC, mrblond1n commented on src/script/order.js
> +                    answ_window.classList.toggle('false');
похоже boolean класс нигде не используется. Может быть можно тут сократить код?)

2022-09-06 08:28 UTC, mrblond1n commented on src/script/order.js
> +        if(answ_window.classList.contains('true')) {
не совсем понимаю зачем это нужно

2022-09-06 08:28 UTC, mrblond1n commented on src/script/order.js
> +        return valid;
выглядит так, будто можно сократить

2022-09-07 11:45 UTC, merged